# Generated by Django 4.2.2 on 2023-06-21 14:28

from django.db import migrations, models
import quotes.models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0004_alter_tag_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'ordering': ['fullname']},
        ),
        migrations.AlterModelOptions(
            name='quote',
            options={'ordering': ['author']},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='author',
            name='photo',
            field=models.ImageField(blank=True, upload_to=quotes.models.author_photo_path),
        ),
    ]
